name: CI

on:
  push:
    branches: 
      - ci_demo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check for script working
      run: echo Hello, world!
