name: CI

on:
  push:
    branches: 
      - ci_demo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Trying to have gcloud sdk
      run: |
        curl https://sdk.cloud.google.com | bash
        exec -l $SHELL
        gcloud init --disable-prompts
        
